version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      # - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/plot-twist:delegated
      - ../rambot/data:/plot-twist/data
      - ../rambot/to_convert:/plot-twist/to_convert
      - ../rambot/public_gifs:/plot-twist/public/gifs
    environment:
      DB_PASSWORD: postgres
      RAILS_ENV: development
      BOT_TOKEN: 'mymagicaltoken'
      BOT_USERNAME: 'my magical username'
      HOST: 'your.server/url'
      LOCKUP_CODEWORD: 'secret'
      LOCKUP_HINT: 'Something that you do not tell everyone.'
  db:
    image: postgres
    volumes:
      # where to put your db
      - ../rambot/db_persistent_folder:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres # do not change
      POSTGRES_DB: postgres # do not change
    ports:
      - 5432:5432
  # web:
  #   build: .
  #   command: rails server -p 3000 -b '0.0.0.0'
  #   # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   volumes:
  #     # current folder, mandatory
  #     # data folder containing both .srt and .webm files
  #     # folder where to convert video files to .webm
  #     # folder where to save the created gifs (mp4)
  #   ports:
  #     - "3000:3000"
  #     - "80:80"
  #     - "88:88"
  #     - "8443:8443"
  #   environment:
  #     # SKIP_FILE_CONVERSION: 'true'
  #     HOST: 'your.server/url'
  #     # TELEGRAM_WEBHOOK_LINK: 'false'
  #     # ROOT_PATH: '/'
  #     # PORT: 443
  #     # BOT_SERVER: ''
  #     DB_PASSWORD: postgres
  #   depends_on:
  #     - db
