version: "3.9"
services:
  web:
    image: martinogiacchetti/plot_twist:latest
    volumes:
      # data folder containing both .srt and .webm files
      - ../rambot/data:/plot-twist/data
      # folder where to convert video files to .webm
      - ../rambot/to_convert:/plot-twist/to_convert
      # folder where to save the created gifs (mp4)
      - ../rambot/public_gifs:/plot-twist/public/gifs
    ports:
      - "3000:80"
      # - "443:443"

    environment:
      DB_HOST: postgres # same as db service name
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: plot_tiwst
      BOT_TOKEN: 'mymagicaltoken'
      BOT_USERNAME: 'my magical username'
      HOST: 'your.server/url'
      LOCKUP_CODEWORD: 'secret'
      LOCKUP_HINT: 'Something that you do not tell everyone.'
      # SKIP_FILE_CONVERSION: 'true'
      # TELEGRAM_WEBHOOK_LINK: 'false'
      # ROOT_PATH: '/'
      # PORT: 443
      # BOT_SERVER: ''
      SECRET_KEY_BASE: 'my secret key'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: plot_tiwst
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../rambot/db_persistent_folder:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
