version: "3.9"
services:
  web:
    image: martinogiacchetti/plot_twist:latest
    volumes:
      # data folder containing both .srt and .webm files
      - ../rambot/data:/home/app/webapp/data
      # folder where to save the created gifs (mp4)
      - ../rambot/public_gifs:/home/app/webapp/public/gifs
      - ./.env.production:/home/app/webapp/.env.production
      - ./cert/website.fullchain.pem:/etc/letsencrypt/live/npm-1/fullchain.pem
      - ./cert/website.privkey.pem:/etc/letsencrypt/live/npm-1/privkey.pem
    ports:
      - "3000:80"
      - "88:443"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_DB: plot_tiwst_production # Must be same name as in rails app
      POSTGRES_USER: postgres # don't change
      POSTGRES_PASSWORD: postgres # don't change
    volumes:
      - ../rambot/db_persistent_folder:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
